# Generated by Django 2.2 on 2021-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
