# Generated by Django 2.2 on 2021-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210309_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=64, unique=True, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='newnews',
            name='header',
            field=models.CharField(max_length=100, verbose_name='Titulo del contenido'),
        ),
        migrations.AddField(
            model_name='newnews',
            name='categoriess',
            field=models.ManyToManyField(help_text='Es siempre necesario este campo', to='news.Categories'),
        ),
    ]
