# Generated by Django 2.2 on 2021-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210326_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newnews',
            name='categoriess',
        ),
        migrations.AddField(
            model_name='newnews',
            name='categoriess',
            field=models.ForeignKey(default=1, help_text='Es siempre necesario este campo', on_delete=django.db.models.deletion.CASCADE, to='news.Categories'),
            preserve_default=False,
        ),
    ]
