# Generated by Django 2.2 on 2021-03-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210326_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newnews',
            name='categoriess',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
